name: Java Project Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        
    - name: Clone input repository
      run: |
        git clone ${{ secrets.INPUT_REPO_URL }} input-repo
      env:
        INPUT_REPO_URL: ${{ github.event.inputs.repo_url }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r input-repo/requirements.txt
        echo "installation done ----------------"


    - name: Run Python script
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        python input-repo/main.py
